"""add action policies

Revision ID: d7d89b1f9794
Revises: e0c6d85489cf
Create Date: 2026-09-11 06:29:02.741800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd7d89b1f9794'
down_revision: Union[str, Sequence[str], None] = 'e0c6d85489cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_policies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=150), nullable=False),
    sa.Column('resource', sa.String(length=150), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('approval_for', sa.String(length=50), nullable=True),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_policies_action'), 'action_policies', ['action'], unique=False)
    op.create_index(op.f('ix_action_policies_is_active'), 'action_policies', ['is_active'], unique=False)
    op.create_index(op.f('ix_action_policies_resource'), 'action_policies', ['resource'], unique=False)
    op.create_index(op.f('ix_action_policies_tenant_id'), 'action_policies', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_action_policies_tenant_id'), table_name='action_policies')
    op.drop_index(op.f('ix_action_policies_resource'), table_name='action_policies')
    op.drop_index(op.f('ix_action_policies_is_active'), table_name='action_policies')
    op.drop_index(op.f('ix_action_policies_action'), table_name='action_policies')
    op.drop_table('action_policies')
    # ### end Alembic commands ###
